# Site settings
title: Milk + Honey
email: info@milkandhoneycrew.com
url: http://milkandhoneycrew.com
description: "Milk + Honey is a music collective based out of Bellingham, WA."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#fcbb11'

# Footer settings
footer: Milk + Honey

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/milkandhoneycrew
  - title: twitter
    url: https://twitter.com/milkhoneycrew
  - title: instagram
    url: https://www.instagram.com/milkandhoneycrew
  - title: soundcloud
    url: https://soundcloud.com/milkandhoneycrew

# Build settings
markdown: kramdown
permalink: pretty
